#!/bin/bash

echo "Executing Docker Brutal Cleanup"

echo "Delete all containers"
containers=$(docker ps -a -q)
if [ "$containers" != '' ]; then
    docker rm -f $containers
else
    echo 'No containers to remove'
fi

echo "Delete all volumes"
volumes=$(docker volume ls -q)
if [ "$volumes" != '' ]; then
    docker volume rm -f $volumes
else
    echo 'No volumes to remove'
fi

$(dirname "$0")/docker-cleanup
