#!/bin/bash

echo "Executing Docker Really Brutal Cleanup"

echo "Delete all images"
images=$(docker image ls -a -q)
if [ "$images" != '' ]; then
    docker image rm --force $images
else
    echo 'No images to remove'
fi

$(dirname "$0")/docker-brutal-cleanup
