#!/bin/bash

# Todo: functionise this and clean up the commands

echo "Executing Docker Really Brutal Cleanup"

$(dirname "$0")/docker-brutal-cleanup

echo "Delete all images"
images=$(docker image ls -a -q)
if [ "$images" != '' ]; then
    docker image rm --force $images
else
    echo 'No images to remove'
fi
