name: CI
on:
    push:
        branches: [main]
    pull_request:
jobs:
    marun-setup:
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Run Setup
              run: ./src/setup.sh
              env:
                  GIT_USER_NAME: Name does not matter for build
                  GIT_USER_EMAIL: email-does@not.matter.either
