name: CI
on:
    push:
        branches: [main]
    pull_request:
jobs:
    run-setup:
        runs-on: macos-12
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Debug Information
              run: |
                pwd
                ls -al
                sw_vers
                zsh --version
                echo "$SHELL"
            - name: Run Full Setup
              run: ./src/setup.sh
              env:
                  # Needed to prevent it stopping and asking you to add them
                  GIT_USER_NAME: Name does not matter for build
                  GIT_USER_EMAIL: email-does@not.matter.either
                  SSH_USER_EMAIL: email-does@not.matter.either
            - name: Run Config Only Setup
              run: ./src/setup.sh -c
              env:
                # Needed to prevent it stopping and asking you to add them
                GIT_USER_NAME: Name does not matter for build
                GIT_USER_EMAIL: email-does@not.matter.either
                SSH_USER_EMAIL: email-does@not.matter.either
