name: CI
on:
    push:
        branches: [main]
    pull_request:
jobs:
    run-setup:
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Debug Information
              run: |
                pwd
                ls -al
                sw_vers
            - name: Run Setup
              run: |
                touch /Users/runner/.zshrc
                ./src/setup.sh
              env:
                  # Needed to prevent it stopping and asking you to add them
                  GIT_USER_NAME: Name does not matter for build
                  GIT_USER_EMAIL: email-does@not.matter.either
