name: SmokeTests

on:
  push:

jobs:
  smoke-tests:
    # Todo: Add a run that actually installs a few of the things
    name: Config-only run
    runs-on: macos-latest
    steps:
      # The setup script does a `git pull`, so make sure we have a proper named branch.
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      # All groups off so, keeping the run fast and side-effect-free.
      - name: Create config file
        run: |
          echo '{
            "includeAllByDefault": false,
            "includeGroup": {},
            "additionalCommands": { "pre": [], "post": [] }
          }' > .config.json

      # Because we don't expect to run config only before it's actually installed the things normally, we need to install asdf here
      - name: Install asdf
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install asdf

      - name: Run setup in config-only mode
        env:
          GIT_USER_NAME: CI
          GIT_USER_EMAIL: ci+git@example.com
          SSH_USER_EMAIL: ci@example.com
        run: ./src/setup.sh -c
